language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 5.5.9
  - hhvm
  - nightly
before_script: 
  - curl -sS https://getcomposer.org/installer | php
  - composer install  
script: phpunit --configuration ./phpunit.xml

